# Generated by Django 3.1.3 on 2023-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
